### ISSUE TITLE
Update image of Shobanadri

### ISSUE THREAD

**Issue by VinayakTekade** [aravindvnair99/FACE-Amrita-Bengaluru#103]
- Image of Shobhanadri needs to be updated in Members page as well as in home page

**Comment by aravindvnair99** [comment]
@VinayakTekade can this be closed?

**Comment by VinayakTekade** [comment]
We don't have the image of Shobanadri, should we remove him from the list?

**Comment by aravindvnair99** [comment]
> We don't have the image of Shobanadri, should we remove him from the list?

@VinayakTekade Yes, go ahead. Keep only those people whom you have pictures of. We got no time to waste.

**Comment by aravindvnair99** [comment]
@VinayakTekade I'm closing the issue. Remove all people whom we don't have pictures of from the website.
