### ISSUE TITLE
ACMW enhancements

### ISSUE THREAD

**Issue by aravindvnair99** [aravindvnair99/FACE-Amrita-Bengaluru#117]
- Don't use `center` tags. Use CSS Style instead.
- Use HTML5 everywhere.
- Put `alt` properly for all images.

**Comment by aravindvnair99** [comment]
@PriyaaIyer Any updates?

**Comment by VinayakTekade** [comment]
Please use the same UI UX design as ACM so that the front end architecture feels complete.
