### ISSUE TITLE
Visibility of the logo on the navbar

### ISSUE THREAD

**Issue by Gandheesh-SA** [aravindvnair99/FACE-Amrita-Bengaluru#134]
Description of the bug:
The ACM-STUDENT CHAPTER logo looks subtle, light and transparent, where as on the external pages linked it looks perfectly fine.

**To Reproduce**
1. Go to https://faceaseb.com/ACM.
2. You shall notice a light,transparent logo at the top left.
3. As you scroll down you shall further notice a subtle and light logo or navbar id.
4. After noticing on main page click on any external link( ex: Go to 
    https://faceaseb.com/ACM_Members). 
5. You shall notice the logo and navbar to be perfectly fine.

*Screenshots**

![Desktop Screenshot 2020 03 24 - 22 21 00 36](https://user-images.githubusercontent.com/56604198/77453938-ea2ac580-6e1d-11ea-92ad-50b1b6172a58.png)
![Desktop Screenshot 2020 03 24 - 22 20 43 11](https://user-images.githubusercontent.com/56604198/77453959-f0b93d00-6e1d-11ea-813f-504409811921.png)
![Desktop Screenshot 2020 03 24 - 22 20 55 15](https://user-images.githubusercontent.com/56604198/77453967-f1ea6a00-6e1d-11ea-9a04-f4903b75888e.png)

Desktop 
  Windows 10 1903 -Operating System
  Google Chrome

**Comment by aravindvnair99** [comment]
@VinayakTekade Make the font of the image a bit bolder. That should fix this. If you have other alternatives, you may implement the same.

**Comment by aravindvnair99** [comment]
@PriyaaIyer You can work with him as you made the logo.
