### ISSUE TITLE
Alignment of members

### ISSUE THREAD

**Issue by adithyaRocks** [aravindvnair99/FACE-Amrita-Bengaluru#136]
**Describe the bug**
The Members arent displayed 

**To Reproduce**
1. Go to 'https://faceaseb.com/ACMW_Members'
2. Scroll down to 'The team'

**Expected behavior**
Should be Inside well aligned boxes
![WhatsApp Image 2020-03-24 at 10 09 39 PM](https://user-images.githubusercontent.com/55869002/77456368-23186980-6e21-11ea-929e-6e7889ce0945.jpeg)

**Comment by PriyaaIyer** [comment]
The issue has been resolved. New code doesn't have any bugs.

**Comment by aravindvnair99** [comment]
> The issue has been resolved. New code doesn't have any bugs.

@PriyaaIyer 

1. Alignment is irregular

![image](https://user-images.githubusercontent.com/22199259/77650448-86290e00-6f91-11ea-8e06-67067c51ee3c.png)

2. Few images are missing

![image](https://user-images.githubusercontent.com/22199259/77650514-9f31bf00-6f91-11ea-95d4-034b6c61e485.png)

**Comment by Shreya1304** [comment]
resolved.

**Comment by aravindvnair99** [comment]
@Shreya1304 your photo is missing

![image](https://user-images.githubusercontent.com/22199259/77766458-afb36980-7065-11ea-984c-91ad75948e8d.png)

**Comment by aravindvnair99** [comment]
Also @Shreya1304 , this photo is not straight:

![image](https://user-images.githubusercontent.com/22199259/77766936-5566d880-7066-11ea-87cf-ae13be592a59.png)

And this irregular:

![image](https://user-images.githubusercontent.com/22199259/77766977-66afe500-7066-11ea-9313-399e165adb2a.png)
