### ISSUE TITLE
SIG box alignment

### ISSUE THREAD

**Issue by adithyaRocks** [aravindvnair99/FACE-Amrita-Bengaluru#137]
**Describe the bug**
The button needs to be aligned properly

**To Reproduce**
1. Go to 'https://faceaseb.com/ACMW#'
2. Scroll down to 'SIG @ AMRITA'
3. See error

**Expected behavior**
Should be aligned
![WhatsApp Image 2020-03-24 at 10 13 37 PM](https://user-images.githubusercontent.com/55869002/77456990-0d577400-6e22-11ea-8498-6d38294b2026.jpeg)
.

**Screenshots**

**Comment by aravindvnair99** [comment]
@adithyaRocks Can you confirm if the issue still exists? Looks like it's been fixed.

**Comment by PriyaaIyer** [comment]
Has been resolved localll. Changes haven't appeared online yet
