### ISSUE TITLE
Footer bugs

### ISSUE THREAD

**Issue by Gandheesh-SA** [aravindvnair99/FACE-Amrita-Bengaluru#138]
FIRST:
**Describe the bug**
White space to the left and right of footer section of the website.

**To Reproduce**
1. Go to https://faceaseb.com/ACMW
2. Scroll down to Contact
3. See error

**Expected behavior**
A white space to the left and right of the footer section.

**Screenshots**
![Desktop Screenshot 2020 03 24 - 23 09 31 62](https://user-images.githubusercontent.com/56604198/77458697-a12a3f80-6e24-11ea-8892-7e5ffc958590.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Lenovo Legion Laptop
 - OS: Windows 10 1903
 - Browser Google Chrome
SECOND:
**Describe the bug**
A unnecessary contact us in the footer section.

**To Reproduce**
1. Go to https://faceaseb.com/ACMW
2. Scroll down to Contact Us section

**Expected behavior**
An unexpected contact us line above the contact number.
Screenshot
![Desktop Screenshot 2020 03 24 - 23 09 31 62_LI](https://user-images.githubusercontent.com/56604198/77459647-0a5e8280-6e26-11ea-98d8-6754bcf7412d.jpg)

**Desktop (please complete the following information):**
Lenovo Legion Laptop
Windows 10 1903
Google Chrome

**Comment by Gandheesh-SA** [comment]
Merged #139 with #138

**Comment by PriyaaIyer** [comment]
Issue fixed. Will be resolved once new code is updated

**Comment by aravindvnair99** [comment]
> Issue fixed. Will be resolved once new code is updated

![image](https://user-images.githubusercontent.com/22199259/77649933-a86e5c00-6f90-11ea-9529-0fdbb61085f1.png)

@PriyaaIyer The white space to the left and right of the footer section continues to exist.
