### ISSUE TITLE
White space between the navbar and image in ACM-W

### ISSUE THREAD

**Issue by Gandheesh-SA** [aravindvnair99/FACE-Amrita-Bengaluru#141]
**Describe the bug**
A white space between the nav bar and the image

**To Reproduce**
1. Go to https://faceaseb.com/ACMW

2. See error

**Screenshots**

![Desktop Screenshot 2020 03 24 - 23 55 08 67](https://user-images.githubusercontent.com/56604198/77463021-f36e5f00-6e2a-11ea-83f7-3f55ce9b48fa.png)
**Desktop (please complete the following information):**
 Lenovo Legion
Windows 10 1903

**Comment by aravindvnair99** [comment]
Fixed in https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/commit/a26160692978d71bc1f2532f35902d9654b52e8c

**Comment by aravindvnair99** [comment]
Fixed in https://github.com/aravindvnair99/FACE-Amrita-Bengaluru/commit/eb0ba64737033fefa510fc1cf0adb41f3161063d
